// <auto-generated />
namespace Ja.Mvc.Acdf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Pseudo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pseudo));
        
        string IMigrationMetadata.Id
        {
            get { return "201507101446145_Pseudo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
