//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja.Mvc.Acdf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcdfSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcdfSubCategory()
        {
            this.AcdfPhotoes = new HashSet<AcdfPhoto>();
        }
    
        public int SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual AcdfCategory AcdfCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcdfPhoto> AcdfPhotoes { get; set; }
    }
}
