//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja.Mvc.Acdf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcdfEntities : DbContext
    {
        public AcdfEntities()
            : base("name=AcdfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcdfCategory> AcdfCategories { get; set; }
        public virtual DbSet<AcdfPhoto> AcdfPhotoes { get; set; }
        public virtual DbSet<AcdfSubCategory> AcdfSubCategories { get; set; }
        public virtual DbSet<AcdfGuessBook> AcdfGuessBooks { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
